<!-- =============================================== -->

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">

            <div class="col-md-12">
                <!-- Horizontal Form -->
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Editar Post</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form class="form-horizontal" method="post" action="<?=SITE_URL ."post/editar/"?>">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="inputTitulo" class="col-sm-2 control-label">Titulo</label>
                                <input type="hidden" name="inputId" value="<?= (isset($this->datosPost[0]['id'])) ? $this->datosPost[0]['id'] :''?>">
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputTitulo" name="inputTitulo" placeholder="Titulo" value="<?= (isset($this->datosPost[0]['titulo'])) ? $this->datosPost[0]['titulo'] :''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputCuerpo" class="col-sm-2 control-label">Cuerpo</label>

                                <div class="col-sm-10">
                                    <textarea name="inputCuerpo" class="form-control" id="inputCuerpo" cols="30" rows="10"><?= (isset($this->datosPost[0]['cuerpo'])) ? $this->datosPost[0]['cuerpo'] :''?></textarea>
                                </div>
                            </div>

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="submit" class="btn btn-info pull-right">Actualizar Post</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
                <!-- /.box -->

            </div>
            <!--/.col (right) -->
        </div>
        <!-- /.row -->
    </section>

</div>
<!-- /.content-wrapper -->

