<!-- =============================================== -->

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Lista de Post</h3>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th>ID</th>
                        <th>Titulo</th>
                        <th>Date</th>
                        <th>Estado</th>
                        <th>Contenido</th>
                        <th>Accion</th>
                    </tr>

                    <?php if(isset($this->posts)): foreach ($this->posts as $post): ?>
                    <tr>
                        <td><?= $post['id']?></td>
                        <td><?= $post['titulo']?></td>
                        <td>11-7-2014</td>
                        <td><span class="label label-success">Approved</span></td>
                        <td><?= substr($post['cuerpo'],0,90)?></td>
                        <td>
                            <a class="btn btn-block btn-primary" href="<?= SITE_URL.'post/editar/'.$post['id']?>"><i class="fa fa-edit"></i></a>

                        </td>
                        <td>
                            <a class="btn btn-block btn-danger" href="<?= SITE_URL.'post/eliminar/'.$post['id']?>"><i class="fa fa-remove"></i></a>
                        </td>

                    </tr>
                    <?php endforeach; endif;?>
                </table>
            </div>
            <!-- /.box-body -->

        </div>
        <a href="<?= SITE_URL.'post/nuevo/'?>" class="btn btn-primary"><i class="fa fa-plus"></i> Insertar Nuevo Post</a>

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

